# Configuration file for Credit Card Fraud Detection

# Data Configuration
data:
  raw_data_path: "data/raw/creditcard.csv"
  processed_data_path: "data/processed/"
  
# Preprocessing Configuration
preprocessing:
  test_size: 0.3
  random_state: 42
  features_to_scale: ["Time", "Amount"]

# Model Configuration
models:
  save_path: "models/saved_models/"
  
  # Individual model parameters
  knn:
    n_neighbors: 5
    
  logistic_regression:
    max_iter: 1000
    random_state: 42
    
  svm:
    probability: true
    random_state: 42
    
  decision_tree:
    random_state: 42
    
  random_forest:
    n_estimators: 100
    random_state: 42
    
  gradient_boost:
    random_state: 42

# Evaluation Configuration
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score", "roc_auc", "pr_auc"]
  primary_metric: "f1_score"

# Visualization Configuration
visualization:
  save_plots: true
  plots_path: "results/plots/"
  figure_size: [10, 8]
  dpi: 300

# Logging Configuration
logging:
  level: "INFO"
  log_file: "fraud_detection.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"